CoavBundle\Entity\PlaneModel:
    type: entity
    table: null
    repositoryClass: CoavBundle\Repository\PlaneModelRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        model:
            type: string
            length: 255
        manufacturer:
            type: string
            length: 255
        cuiseSpeed:
            type: integer
            nullable: true
        nbSeat:
            type: integer
            nullable: true
        status:
            type: string
            length: 255
    lifecycleCallbacks: {  }
