terrain_index:
    path:     /
    defaults: { _controller: "CoavBundle:Terrain:index" }
    methods:  GET

terrain_show:
    path:     /{id}/show
    defaults: { _controller: "CoavBundle:Terrain:show" }
    methods:  GET

terrain_add:
    path:     /add
    defaults: { _controller: "CoavBundle:Default:Add" }
    methods:  GET
